export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';
export const POSTS_FETCHED = 'POSTS_FETCHED';

export const POST_UPVOTED = 'POST_UPVOTED';
export const POST_DOWNVOTED = 'POST_DOWNVOTED';

export const POST_FETCHED = 'POST_FETCHED';
export const POST_COMMENTS_FETCHED = 'POST_COMMENTS_FETCHED';

export const COMMENT_UPVOTED = 'COMMENT_UPVOTED';
export const COMMENT_DOWNVOTED = 'COMMENT_DOWNVOTED';